Bump go to 1.17 and k8s to 1.22.3
kubernetes-sigs/kubebuilder-declarative-pattern pull request #189
Opened 2021-11-16 21:22 UTC by ryantking

**What this PR does / why we need it**:

Bumps go 1.16 -> 1.17 and k8s.io/... deps 1.22.2 -> 1.22.3

**Which issue(s) this PR fixes**:

Part of https://github.com/kubernetes-sigs/kubebuilder/issues/2421

**Special notes for your reviewer**:

**Additional documentation**:

2021-11-17 17:42 UTC, camilamacedo86 commented
/ok-to-test

2021-11-17 17:43 UTC, camilamacedo86 commented on examples/guestbook-operator/go.mod
> +require (
/hold 

we ought to not have twice the required
we need to remove the indirect ones. 
to upgrade the go version we ought to not change the deps.

2021-11-17 17:44 UTC, camilamacedo86 requested changes
Thank you for your contribution 🥇 
Please, see; https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/189/files#r751483417

2021-11-19 17:07 UTC, camilamacedo86 approved these changes

2021-11-19 17:07 UTC, camilamacedo86 commented
/approved
/lgtm

2021-11-19 17:08 UTC, camilamacedo86 commented
/hold cancel

2021-11-19 17:08 UTC, camilamacedo86 commented
/approved

2021-11-19 19:19 UTC, atoato88 commented
It's LGTM also.
Sorry for late response.

2021-11-30 16:29 UTC, camilamacedo86 commented
/approved

2021-12-01 00:13 UTC, atoato88 commented
/approve

2021-12-01 00:19 UTC, merged